// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKBcTgfAhh4vmfQs7rRoIQ1v9B0bJlyts',
    appId: '1:208326592859:android:66a5593468ed631439327e',
    messagingSenderId: '208326592859',
    projectId: 'market-beacon-74abb',
    databaseURL: 'https://market-beacon-74abb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'market-beacon-74abb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_idB7w6Y0hnmJgAqRMfxvzzC8ToE0S00',
    appId: '1:208326592859:ios:cd881115f2ba936039327e',
    messagingSenderId: '208326592859',
    projectId: 'market-beacon-74abb',
    databaseURL: 'https://market-beacon-74abb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'market-beacon-74abb.appspot.com',
    androidClientId: '208326592859-drg58iqdq0rsb0tudduad4lp5kj8un62.apps.googleusercontent.com',
    iosClientId: '208326592859-55asfr5vqv9u9qgtgtk2ccjs4sqanle6.apps.googleusercontent.com',
    iosBundleId: 'com.finsicle.marketBeacon',
  );
}
